-- ============================================
-- Brazilian E-commerce Business Questions
-- ============================================

-- 1. How many orders are there for each order status?

-- 2. What is the total revenue generated by each payment type?

-- 3. Which top 5 cities have the highest number of orders?

-- 4. What are the highest, lowest, and average product prices?

-- 5. How are orders distributed across different months?

-- 6. What is the total revenue generated overall?

-- 7. Who are the top 10 customers based on total spending?

-- 8. Which are the top 10 best-selling products?

-- 9. How does revenue vary month by month?

-- 10. Which cities generate the highest revenue?

-- 11. What are the top 10 highest-value orders?

-- 12. What is the average order value?
